### ISSUE TITLE
Change github io page to osgenepal.github.io

### ISSUE THREAD

**Issue by kshitijrajsharma** [osgeonepal/osgeonepal.github.io#34]
Currently github io page is under / rollingdoc , plan is to change it to default github.io page so it would make more sense for people where main website will be

**Comment by Pratichhya** [comment]
Is this a task within the coding party? or is someone among us already assigned?

**Comment by iamtekson** [comment]
This task is already completed dd! I will close it now. The task was about changing the url of our landing page.
